<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <RollForward>Major</RollForward>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <!-- 单文件发布，不打包 .NET 运行时 -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>

    <NoWarn>$(NoWarn);SYSLIB0003;SYSLIB0004;SYSLIB0051;CS0672;CA1416</NoWarn>
    <StartupObject>War3Trainer.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReaLTaiizor" Version="3.8.2.1" />
  </ItemGroup>

</Project>